line-length = 120

[format]
docstring-code-format = true
docstring-code-line-length = 80

[lint]
select = [
    "A",
    "ARG",
    "ASYNC",
    "B",
    "BLE",
    "C",
    "COM818",
    "COM819",
    "DTZ",
    "E",
    "EM",
    "EXE",
    "F",
    "FA",
    "FBT",
    "FLY",
    "G",
    "I",
    "ICN",
    "INT",
    "ISC002",
    "ISC003",
    "LOG",
    "N",
    "PERF",
    "PGH",
    "PIE",
    "PLC",
    "PLE",
    "PLR",
    "PLW",
    "PT",
    "PYI",
    "RET",
    "RSE",
    "RUF00",
    "RUF01",
    "RUF020",
    "RUF100",
    "S1",
    "S6",
    "SIM",
    "SLF",
    "T10",
    "T20",
    "TCH",
    "TD004",
    "TD005",
    "TD006",
    "TD007",
    "TID",
    "TRY",
    "UP",
    "W2",
    "W5",
    "W6",
]

[lint.per-file-ignores]
"**/scripts/*" = ["S603", "T201"]
"**/{test,tests}/**/*" = ["PLC1901", "PLR2004", "PLR6301", "S", "SLF"]

[lint.flake8-tidy-imports]
ban-relative-imports = "all"

[lint.isort]
known-first-party = ["yt_dlp_fixupmtime"]

[lint.flake8-pytest-style]
fixture-parentheses = false
mark-parentheses = false
