name: main

on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      code: ${{ steps.filter.outputs.code }}
    steps:
    - uses: actions/checkout@v3
    - id: filter
      uses: dorny/paths-filter@v2
      with:
        filters: |
          code:
            - '**/*fixup_mtime.py'
            - '.github/workflows/**'
  lint:
    needs: changes
    if: github.event_name == 'push' || needs.changes.outputs.code == 'true'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
    - name: Install flake8
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8
    - name: Lint with flake8
      run: flake8 .
  test:
    needs: changes
    if: github.event_name == 'push' || needs.changes.outputs.code == 'true'
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install yt-dlp
    - name: Run tests
      run: |
        python -m unittest discover -v -s test -p 'test_*.py'
