name: main

on:
  pull_request:
    branches: [main, master]
  push:
    branches: [main, master]
  schedule:
    - cron: "0 0 * * 1"

env:
  PIP_DISABLE_PIP_VERSION_CHECK: 1
  PIP_TRUSTED_HOST: "pypi.python.org pypi.org files.pythonhosted.org"

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  changes:
    runs-on: ubuntu-22.04
    if: github.event_name != 'schedule'
    permissions:
      contents: read
      pull-requests: read
    outputs:
      core: ${{ steps.filter.outputs.core }}
      workflow: ${{ steps.filter.outputs.workflow }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          persist-credentials: false

      - uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d
        id: filter
        with:
          list-files: json
          filters: |
            core:
              - added|modified: 'yt_dlp_plugins/**/*.py'
              - added|modified: 'test/**/*.py'
            workflow:
              - added|modified: '.github/workflows/main.yml'

  lint:
    runs-on: ubuntu-22.04
    needs: changes
    if: needs.changes.outputs.core == 'true' || needs.changes.outputs.workflow == 'true'
    permissions:
      contents: read
      pull-requests: read
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          persist-credentials: false

      - uses: astral-sh/ruff-action@0ce1b0bf8b818ef400413f810f8a11cdbda0034b
        with:
          version-file: pyproject.toml

      - run: ruff format --check

  test:
    runs-on: ${{ matrix.os }}
    needs: [changes, lint]
    permissions:
      contents: read
      pull-requests: read
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, windows-2022]
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13", "pypy3.10"]
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          persist-credentials: false

      - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1
        with:
          python-version: ${{ matrix.python-version }}

      - uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39
        with:
          enable-cache: true
          cache-suffix: ${{ matrix.python-version }}
          cache-dependency-glob: "**/pyproject.toml"

      - name: Setup venv
        run: uv sync --python "${{ matrix.python-version }}"

      - name: Test
        run: uv run pytest "test/test_fixup_mtime.py"

  scheduled-test:
    runs-on: ${{ matrix.os }}
    if: github.event_name == 'schedule'
    permissions:
      contents: read
      pull-requests: read
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, windows-2022]
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13", "pypy3.10"]
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          persist-credentials: false

      - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1
        with:
          python-version: ${{ matrix.python-version }}

      - uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39
        with:
          enable-cache: true
          cache-suffix: ${{ matrix.python-version }}
          cache-dependency-glob: "**/pyproject.toml"

      - name: Setup venv
        run: uv sync --python "${{ matrix.python-version }}"

      - name: Test
        run: uv run pytest "test/test_fixup_mtime.py"
