name: main

on:
  pull_request:
    branches: [main, master]
  push:
    branches: [main, master]

env:
  PIP_DISABLE_PIP_VERSION_CHECK: 1
  PIP_TRUSTED_HOST: "pypi.python.org pypi.org files.pythonhosted.org"

jobs:
  changes:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      pull-requests: read
    outputs:
      core: ${{ steps.filter.outputs.core }}
      workflow: ${{ steps.filter.outputs.workflow }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36
        id: filter
        with:
          list-files: json
          filters: |
            core:
              - added|modified: 'yt_dlp_plugins/**/*.py'
              - added|modified: 'test/**/*.py'
            workflow:
              - added|modified: '.github/workflows/main.yml'

  lint:
    runs-on: ubuntu-22.04
    needs: changes
    if: needs.changes.outputs.core == 'true' || needs.changes.outputs.workflow == 'true'
    permissions:
      contents: read
      pull-requests: read
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - uses: astral-sh/ruff-action@a7b1296fb5bd3ebb270731d1782bf05a97806e29
        with:
          version-file: pyproject.toml

      - run: ruff format --check

  test:
    runs-on: ${{ matrix.os }}
    needs: [changes, lint]
    permissions:
      contents: read
      pull-requests: read
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, windows-2022]
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13", "pypy3.9"]
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38
        with:
          python-version: ${{ matrix.python-version }}

      - uses: astral-sh/setup-uv@4db96194c378173c656ce18a155ffc14a9fc4355

      - name: Setup venv
        run: uv sync --frozen --python "${{ matrix.python-version }}"

      - name: Test
        run: uv run pytest "test/test_fixup_mtime.py"
